# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1037, 789)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.camera = QtWidgets.QLabel(Form)
        self.camera.setAlignment(QtCore.Qt.AlignCenter)
        self.camera.setObjectName("camera")
        self.verticalLayout_2.addWidget(self.camera)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logger = QtWidgets.QTextBrowser(Form)
        self.logger.setObjectName("logger")
        self.horizontalLayout.addWidget(self.logger)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.start = QtWidgets.QPushButton(Form)
        self.start.setMinimumSize(QtCore.QSize(0, 60))
        self.start.setObjectName("start")
        self.verticalLayout.addWidget(self.start)
        self.resume = QtWidgets.QPushButton(Form)
        self.resume.setMinimumSize(QtCore.QSize(0, 60))
        self.resume.setObjectName("resume")
        self.verticalLayout.addWidget(self.resume)
        self.end = QtWidgets.QPushButton(Form)
        self.end.setMinimumSize(QtCore.QSize(0, 60))
        self.end.setObjectName("end")
        self.verticalLayout.addWidget(self.end)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.setStretch(0, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.camera.setText(_translate("Form", "camera"))
        self.start.setText(_translate("Form", "start"))
        self.resume.setText(_translate("Form", "stop"))
        self.end.setText(_translate("Form", "resume"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
